### ISSUE TITLE
Title area and content area keep shifting to the right and down

### ISSUE THREAD

**Issue by Soham-glitch** [Soham-glitch/Keeper-app#2]
# What is the issue?
Whenever adding a new title and content the form area keeps shifting to the right and down

## How to reproduce?
run the project on the local environment and try to add some content and we will notice the issue.

Does anything need to know?

**Comment by vishalpawarR** [comment]
@Soham-glitch can you please provide the screenshot of the issue may be I can help properly to this.

**Comment by vishalpawarR** [comment]
Please share the more info may be I can try to help you in better way.

**Comment by Soham-glitch** [comment]
Sure. Feel free to raise pr. It's more like a styling issue. the problem in the CSS file

![Keeper - Google Chrome 15-06-2023 08_43_56 PM](https://github.com/Soham-glitch/Keeper-app/assets/76726887/eafc3a14-bd8b-406a-9d04-db2b97cda4b9)

![Keeper - Google Chrome 15-06-2023 08_43_44 PM](https://github.com/Soham-glitch/Keeper-app/assets/76726887/51f06290-8446-4d62-a62f-965bcf7f4651)

**Comment by Soham-glitch** [comment]
@vishalpawarR I have provided screenshots please look at them

**Comment by vishalpawarR** [comment]
@Soham-glitch What is the expected result? Do you want the new things to come below? and Keeping the New box at top? I think this will make adding new notes easy for adding instead of scrolling down for adding the note!

**Comment by Soham-glitch** [comment]
Yeah absolutely! The title and content box should be at the top.

**Comment by vishalpawarR** [comment]
Accept the PR and close it if you like the solution!
https://github.com/Soham-glitch/Keeper-app/pull/3
